server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: come.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 123456
mybatis:
  #标注mybatis配置文件的位置
  config-location: classpath:mapper/sqlmap-config.xml
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
  type-aliases-package: com.example.demo.pojo
  configuration:
    map-underscore-to-camel-case: true

